### ISSUE TITLE
Error getting report

### ISSUE THREAD

**Issue by yul14nrc** [keptn-sandbox/keptn-report#1]
I installed the keptn-report utility and it's showing the following error:

julian@ubuntu:~/go/bin$ cat ~/keptn/reports/sampledata.json | ./keptn-report -out ~/keptn/reports/myreport.pdf
please provide at least one series

attached the sampledata.json used. (convert from .txt to .json)
[sampledata.txt](https://github.com/keptn-sandbox/keptn-report/files/4517290/sampledata.txt)

**Comment by checkelmann** [comment]
Thank you for your input.
I've released a fixed version that skips the chart creation if no history is within the event.
